/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThermoGasLawsRouteImport } from './routes/thermo/gas-laws'
import { Route as FlashcardsReviewRouteImport } from './routes/flashcards/review'
import { Route as FlashcardsDeckRouteImport } from './routes/flashcards/deck'
import { Route as BondsQuizRouteImport } from './routes/bonds/quiz'
import { Route as BondsIntroRouteImport } from './routes/bonds/intro'
import { Route as BondsExamRouteImport } from './routes/bonds/exam'
import { Route as ApiSplatRouteImport } from './routes/api/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThermoGasLawsRoute = ThermoGasLawsRouteImport.update({
  id: '/thermo/gas-laws',
  path: '/thermo/gas-laws',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsReviewRoute = FlashcardsReviewRouteImport.update({
  id: '/flashcards/review',
  path: '/flashcards/review',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsDeckRoute = FlashcardsDeckRouteImport.update({
  id: '/flashcards/deck',
  path: '/flashcards/deck',
  getParentRoute: () => rootRouteImport,
} as any)
const BondsQuizRoute = BondsQuizRouteImport.update({
  id: '/bonds/quiz',
  path: '/bonds/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const BondsIntroRoute = BondsIntroRouteImport.update({
  id: '/bonds/intro',
  path: '/bonds/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const BondsExamRoute = BondsExamRouteImport.update({
  id: '/bonds/exam',
  path: '/bonds/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/bonds/exam': typeof BondsExamRoute
  '/bonds/intro': typeof BondsIntroRoute
  '/bonds/quiz': typeof BondsQuizRoute
  '/flashcards/deck': typeof FlashcardsDeckRoute
  '/flashcards/review': typeof FlashcardsReviewRoute
  '/thermo/gas-laws': typeof ThermoGasLawsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/bonds/exam': typeof BondsExamRoute
  '/bonds/intro': typeof BondsIntroRoute
  '/bonds/quiz': typeof BondsQuizRoute
  '/flashcards/deck': typeof FlashcardsDeckRoute
  '/flashcards/review': typeof FlashcardsReviewRoute
  '/thermo/gas-laws': typeof ThermoGasLawsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/bonds/exam': typeof BondsExamRoute
  '/bonds/intro': typeof BondsIntroRoute
  '/bonds/quiz': typeof BondsQuizRoute
  '/flashcards/deck': typeof FlashcardsDeckRoute
  '/flashcards/review': typeof FlashcardsReviewRoute
  '/thermo/gas-laws': typeof ThermoGasLawsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/$'
    | '/bonds/exam'
    | '/bonds/intro'
    | '/bonds/quiz'
    | '/flashcards/deck'
    | '/flashcards/review'
    | '/thermo/gas-laws'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/$'
    | '/bonds/exam'
    | '/bonds/intro'
    | '/bonds/quiz'
    | '/flashcards/deck'
    | '/flashcards/review'
    | '/thermo/gas-laws'
  id:
    | '__root__'
    | '/'
    | '/api/$'
    | '/bonds/exam'
    | '/bonds/intro'
    | '/bonds/quiz'
    | '/flashcards/deck'
    | '/flashcards/review'
    | '/thermo/gas-laws'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSplatRoute: typeof ApiSplatRoute
  BondsExamRoute: typeof BondsExamRoute
  BondsIntroRoute: typeof BondsIntroRoute
  BondsQuizRoute: typeof BondsQuizRoute
  FlashcardsDeckRoute: typeof FlashcardsDeckRoute
  FlashcardsReviewRoute: typeof FlashcardsReviewRoute
  ThermoGasLawsRoute: typeof ThermoGasLawsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thermo/gas-laws': {
      id: '/thermo/gas-laws'
      path: '/thermo/gas-laws'
      fullPath: '/thermo/gas-laws'
      preLoaderRoute: typeof ThermoGasLawsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards/review': {
      id: '/flashcards/review'
      path: '/flashcards/review'
      fullPath: '/flashcards/review'
      preLoaderRoute: typeof FlashcardsReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards/deck': {
      id: '/flashcards/deck'
      path: '/flashcards/deck'
      fullPath: '/flashcards/deck'
      preLoaderRoute: typeof FlashcardsDeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonds/quiz': {
      id: '/bonds/quiz'
      path: '/bonds/quiz'
      fullPath: '/bonds/quiz'
      preLoaderRoute: typeof BondsQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonds/intro': {
      id: '/bonds/intro'
      path: '/bonds/intro'
      fullPath: '/bonds/intro'
      preLoaderRoute: typeof BondsIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonds/exam': {
      id: '/bonds/exam'
      path: '/bonds/exam'
      fullPath: '/bonds/exam'
      preLoaderRoute: typeof BondsExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSplatRoute: ApiSplatRoute,
  BondsExamRoute: BondsExamRoute,
  BondsIntroRoute: BondsIntroRoute,
  BondsQuizRoute: BondsQuizRoute,
  FlashcardsDeckRoute: FlashcardsDeckRoute,
  FlashcardsReviewRoute: FlashcardsReviewRoute,
  ThermoGasLawsRoute: ThermoGasLawsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './core/router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
